// src/app/projects/Project.tsx
"use client";

export default function Project({ data }: { data: any }) {
  return (
    <a href={data.href}>
      <div className="relative h-80 w-full overflow-hidden rounded-lg bg-white group-hover:opacity-75 sm:aspect-w-2 sm:aspect-h-1 sm:h-64 lg:aspect-w-1 lg:aspect-h-1">
        <img
          src={data.imageSrc}
          alt={data.name}
          className="h-full w-full object-cover object-center"
        />
      </div>
      <p className="mt-6 text-sm text-gray-500">{data.description}</p>
      <p className="text-base font-semibold text-gray-900">{data.name}</p>
    </a>
  );
}

// components/Project.vue
<template>
  <NuxtLink :to="data.href" target="_blank">
    <div
      class="relative h-80 w-full overflow-hidden rounded-lg bg-white group-hover:opacity-75 sm:aspect-w-2 sm:aspect-h-1 sm:h-64 lg:aspect-w-1 lg:aspect-h-1"
    >
      <img
        :src="data.imageSrc"
        class="h-full w-full object-cover object-center"
      />
    </div>
    <h3 class="mt-6 text-sm text-gray-500">
      <a :href="data.href">
        <span class="absolute inset-0" />
        {{ data.name }}
      </a>
    </h3>
    <p class="text-base font-semibold text-gray-900">
      {{ data.description }}
    </p>
  </NuxtLink>
</template>

<script>
export default {
  props: {
    data: {
      name: String,
      href: String,
    },
  },
};
</script>
